### ISSUE TITLE
How to get the return value from a chaincode invoke

### ISSUE THREAD

**Issue by RunshanHu** [sunfish-prj/Service-Ledger#3]
Due to the asynchronisation of chaincode execution, I do not know how to return a value from a chaincode invokation. By default it only returns the transaction id if it succeeds. Do you have any examples of returning customised value from a chaincode invokation? many thanks @andreamargheri @derigo88

**Comment by derigo88** [comment]
From the best of my knowledge you can't do that.

Hyperledger split the chaincdoe execution from the consensus. Actually,
invoked peers execute a chain code but the result is not stored at all, it
is just simulated on their local state. Then they pass the signed
transaction (with the eventual change of the state) to the orderer. If
consensus is achieved every peers commit the transaction.

What you want to do has to be implemented separately through some polling
mechanism which query the ledger.

I'm not aware of any sdk doing this, yet I've not investigated too much
deeply this situation in new sdk versions.

My advice is to look for it on Google, I can't help you more than this
unfortunately.

Cheers
Federico

Il 03 nov 2017 18:18, "Runshan Hu" <notifications@github.com> ha scritto:

**Comment by RunshanHu** [comment]
thank you for your information, Fede @derigo88
